//! Makes upstream's tests/wgsl-errors.rs (a libtest file) runnable as suite `wgsl-errors` of the
//! oracle (src/main.rs), which is a libFuzzer binary: outside a `--test` build rustc drops every
//! `#[test]` function. So this writes to $OUT_DIR
//!   - wgsl_errors.rs: upstream's file with each `#[test]` line blanked (every other line, and so
//!     every line number, unchanged) plus `CASES`, the table of those functions in file order;
//!   - wgsl_errors_mod.rs: `#[path = "<that file>"] mod wgsl_errors;` (a module file keeps upstream's
//!     inner attributes valid; src/main.rs `include!`s this declaration).
//! It fails the build if a `#[test]` line is not followed by `fn <name>() {`, or if it finds none.
//!
//! It also writes ir_decode_testsuite.rs for suite `ir-decode` (src/ir_decode.rs): one check per file
//! of ir-decode/testsuite/ (committed `ir` testsuite inputs, each named by its lowercase-hex SHA-256),
//! in name order, with the bytes embedded (`include_bytes!`): `TESTSUITE` (check name, bytes) and
//! `TESTSUITE_CASES`. It fails the build if that directory is empty or holds a file not named so.

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let src = manifest_dir.join("../../tests/wgsl-errors.rs");
    println!("cargo:rerun-if-changed={}", src.display());
    println!("cargo:rerun-if-changed=build.rs");
    let text = fs::read_to_string(&src).unwrap_or_else(|e| panic!("cannot read {}: {e}", src.display()));

    let mut out = String::with_capacity(text.len() + 4096);
    let mut names: Vec<&str> = Vec::new();
    let mut after_test_attr = false;
    for (index, line) in text.lines().enumerate() {
        if after_test_attr {
            let name = line
                .strip_prefix("fn ")
                .and_then(|rest| rest.strip_suffix("() {"))
                .filter(|n| !n.is_empty() && n.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'));
            match name {
                Some(name) => names.push(name),
                None => panic!(
                    "{}:{}: expected `fn <name>() {{` after `#[test]`, found {line:?}",
                    src.display(),
                    index + 1
                ),
            }
            after_test_attr = false;
        }
        if line.trim() == "#[test]" {
            after_test_attr = true;
        } else {
            out.push_str(line);
        }
        out.push('\n');
    }
    assert!(!after_test_attr, "{}: `#[test]` at end of file", src.display());
    assert!(!names.is_empty(), "{}: no `#[test]` functions found", src.display());

    out.push_str(
        "\n/// Generated by mayhem/oracle/build.rs: every `#[test]` function above, in file order.\n\
         pub(crate) const CASES: &[(&str, fn())] = &[\n",
    );
    for name in &names {
        out.push_str(&format!("    ({name:?}, {name}),\n"));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join("wgsl_errors.rs");
    fs::write(&generated, out).expect("write wgsl_errors.rs");
    let generated = generated.to_str().expect("OUT_DIR is not UTF-8");
    fs::write(
        out_dir.join("wgsl_errors_mod.rs"),
        format!("#[path = {generated:?}]\nmod wgsl_errors;\n"),
    )
    .expect("write wgsl_errors_mod.rs");

    ir_decode_testsuite(&manifest_dir, &out_dir);
}

/// Writes $OUT_DIR/ir_decode_testsuite.rs (see the header).
fn ir_decode_testsuite(manifest_dir: &std::path::Path, out_dir: &std::path::Path) {
    let dir = manifest_dir.join("ir-decode/testsuite");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut files: Vec<(String, PathBuf)> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| {
            let path = entry.expect("read_dir entry").path();
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or_default().to_string();
            assert!(
                name.len() == 64 && name.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b)),
                "{}: not named by a lowercase-hex SHA-256",
                path.display()
            );
            (name, path)
        })
        .collect();
    files.sort();
    assert!(!files.is_empty(), "{}: no testsuite inputs", dir.display());

    let mut table = String::from(
        "/// Generated by mayhem/oracle/build.rs: (check name, bytes) of every ir-decode/testsuite/ input.\n\
         pub(crate) const TESTSUITE: &[(&str, &[u8])] = &[\n",
    );
    let mut cases = String::from(
        "/// Generated by mayhem/oracle/build.rs: suite `ir-decode`, part 2 (one check per testsuite input).\n\
         pub(crate) const TESTSUITE_CASES: &[(&str, fn())] = &[\n",
    );
    for (index, (name, path)) in files.iter().enumerate() {
        let check = format!("testsuite_{}", &name[..16]);
        let path = path.to_str().expect("testsuite path is not UTF-8");
        table.push_str(&format!("    ({check:?}, include_bytes!({path:?})),\n"));
        cases.push_str(&format!("    ({check:?}, || check(TESTSUITE[{index}].0, TESTSUITE[{index}].1)),\n"));
    }
    table.push_str("];\n");
    cases.push_str("];\n");
    fs::write(out_dir.join("ir_decode_testsuite.rs"), table + &cases).expect("write ir_decode_testsuite.rs");
}
